### ISSUE TITLE
Missing captcha response in POST data!

### ISSUE THREAD

**Issue by cuddylier** [hybula/whmcs-turnstile#12] opened 2024-10-16 00:24 UTC
WHMCS version: 8.11.2
PHP verson: 8.1

On the WHMCS ticket creation page, when you enter text in the "Message" box, "Missing captcha response in POST data!" appears just above the Turnstile captcha. The captcha does function properly - if complete then it allows ticket submission and if not, it shows the "hybulaTurnstileError" variable output on a new page.

Screenshot:
![Screenshot 2024-10-16 at 01 18 17](https://github.com/user-attachments/assets/89418643-5331-4533-9793-dbdbe84bc9eb)

**Comment by pRieStaKos** [comment] 2024-10-23 17:54
I can verify this and add that "_Missing captcha response in POST data!_" exists on Admin > General Settings > Mail > Configure Mail Provider too and prevents you from updating/setting the Mail Configuration.

**Comment by dqos** [comment] 2024-10-31 14:20
I cannot reproduce this, which captcha did you use in WHMCS settings? Try disabling it.

@pRieStaKos your issue is not related, but it seems that the hook is catching the post in your admin area. For now, temporarily disable the hook, change settings and re-enable.

With the new official hCaptcha implementation of WHMCS, I am not eager to support further development of this hook.

**Comment by cuddylier** [comment] 2024-10-31 21:22
My captcha is set to "Always Disabled" in General Settings -> Security. I can still reproduce it, I haven't got a very customised WHMCS install.

The issue with WHMCS' official hCaptcha implementation is that hCaptcha requires you to pay $99 per month for the friction free option otherwise 100% of visitors are prompted to complete the painful picture challenge on the free plan. CF Turnstile has none of this pain and no cost.

**Comment by dqos** [comment] 2024-12-06 13:54
I have found both of your issues @pRieStaKos @cuddylier and fixed it both in the latest commit: https://github.com/hybula/whmcs-turnstile/commit/5c7f06569216d9c5631709967738d31116959632

@pRieStaKos your issue has been fixed by disabling captcha when an admin session is found. For some reason the captcha kicks in the admin page, so this doesn't happen anymore.

@cuddylier this was caused by the "Knowledgebase Suggestions" feature, it does a POST request triggering the captcha mechanism. We now check for what fields are posted on the `submitticket.php` form.

**Closed by dqos** 2024-12-06 13:54 UTC

**Comment by cuddylier** [comment] 2024-12-10 22:48
I updated to the latest commit and the captcha no longer shows at all, I downgraded back to the commit prior to this and it shows up fine.

**Comment by dqos** [comment] 2024-12-17 08:23
@cuddylier The captcha will not show up when you are logged in as admin, check my previous comment. Try opening your page in a private window and it should show up.

**Comment by cuddylier** [comment] 2024-12-17 18:02
> @cuddylier The captcha will not show up when you are logged in as admin, check my previous comment. Try opening your page in a private window and it should show up.

Ah, I understand now, apologies. I can confirm all is fine when there's no admin session, thanks.
